apps/cart/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from .views import CartAddView, CartInfoView, CartUpdateView, CartDeleteView

urlpatterns = [
    path('add/', CartAddView.as_view(), name='add'),  # 购物车添加
    re_path(r'^$', CartInfoView.as_view(), name='show'),  # 购物车显示
    re_path(r'^update$', CartUpdateView.as_view(), name='update'),  # 购物车更新
    re_path(r'^delete', CartDeleteView.as_view(), name='delete')  # 删除购物车商品
]

apps/goods/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from apps.goods import views
from apps.goods.views import IndexView, DetailView, ListView

urlpatterns = [
    re_path('^index$', IndexView.as_view(), name='index'),  # 首页
    re_path('goods/(?P<goods_id>\d+)', DetailView.as_view(), name='detail'),  # 根据goods_id查看详情页
    re_path('list/(?P<type_id>\d+)/(?P<page>\d)/', ListView.as_view(), name='list')  # 列表页
]

apps/order/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from apps.order.views import OrderPlaceView, OrderCommitView, OrderPayView, CheckPayView

urlpatterns = [
    re_path(r'^place$', OrderPlaceView.as_view(), name='place'),  # 订单结算
    re_path(r'^commit$', OrderCommitView.as_view(), name='commit'),  # 订单提交后台处理
    re_path(r'^pay$', OrderPayView.as_view(), name='pay'),  # 支付处理
    re_path(r'^check$', CheckPayView.as_view(), name='check')  # 支付处理
]

apps/user/urls.py
from django.urls import path
from django.conf.urls import url
from apps.user.views import (RegisterView, ActiveView, LoginView, UserInfoView, UserOrderView, LoginOutView,
                             UserAddressView)

from django.urls import re_path
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),  # 注册
    re_path('active/(?P<token>.*)/', ActiveView.as_view(), name='active'),  # 激活
    path('login/', LoginView.as_view(), name='login'),  # 登录
    path('logout/', LoginOutView.as_view(), name='logout'),  # 登出
    re_path('^order/(?P<page>\d+)', UserOrderView.as_view(), name='order'),  # 用户中心-订单
    re_path('^$', UserInfoView.as_view(), name='index'),  # 用户中心-信息
    path('address/', UserAddressView.as_view(), name='address'),  # 用户中心-地址
]

dailyfresh/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),  # 富文本编辑器
    url(r'^search', include('haystack.urls')),  # 全文检索框架
    url(r'^user/', include(('user.urls', 'user'), namespace='user')),  # 用户模块
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),  # 购物车模块
    url(r'^order/', include(('order.urls', 'order'), namespace='order')),  # 订单模块
    url(r'^', include(('goods.urls', 'goods'), namespace='goods'))  # 商品模块
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from apps.goods.models import GoodsSKU
from django_redis import get_redis_connection
from django.shortcuts import redirect, reverse
from utils.mixin import LoginRequireMixin


# 添加商品到购物车
# 传递参数 商品id(sku_id) 商品数量(count)

# /cart/add
class CartAddView(View):
    """购物车记录添加"""

    def post(self, request):
        """购物车记录添加"""
        # 获取数据
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 5, 'msg': '请先登录'})
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 0, 'msg': '数据不完整'})

        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 1, 'msg': '数目出错'})

        # 检验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res': 2, 'msg': '商品不存在'})

        # 业务处理
        conn = get_redis_connection('default')
        cart_key = 'cart_%s' % user.id
        # 获取sku_id的值 hget cart_key
        # 如果sku_id在hash中不存在，则返回None
        cart_count = conn.hget(cart_key, sku_id)
        if cart_count:
            # 如果用户hash有记录则追加count
            count += int(cart_count)
        if count > sku.stock:
            return JsonResponse({'res': 4, 'msg': '商品库存不足'})
        conn.hset(cart_key, sku_id, count)

        total_count = conn.hlen(cart_key)
        # 返回应答
        return JsonResponse({'res': 3, 'total_count': total_count, 'msg': '添加成功'})


# /cart/
class CartInfoView(LoginRequireMixin, View):
    """购物车显示页面"""

    def get(self, request):
        user = request.user
        conn = get_redis_connection('default')
        cart_key = 'cart_%s' % user.id
        cart_dict = conn.hgetall(cart_key)
        # cart_dict = {'商品id': 商品数量}
        skus = []
        total_count = 0
        total_price = 0
        for sku_id, count in cart_dict.items():
            sku = GoodsSKU.objects.get(id=sku_id)
            amount = sku.price * int(count)
            # 动态添加属性
            sku.amount = amount
            sku.count = int(count)
            skus.append(sku)

            total_count += int(count)
            total_price += amount

        context = {
            'skus': skus,
            'total_count': total_count,
            'total_price': total_price
        }
        return render(request, 'cart.html', context)


# /cart/update
class CartUpdateView(View):
    """更新购物车数量"""

    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 5, 'msg': '请先登录'})
        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 校验数据
        if not all([sku_id, count]):
            return JsonResponse({'res': 0, 'msg': '数据不完整'})

        try:
            sku_id = int(sku_id)
            count = int(count)
        except:
            return JsonResponse({'res': 1, 'msg': '类型出错'})

        # 判断商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 1, 'msg': '商品不存在'})

        # 更新购物车数量
        conn = get_redis_connection('default')
        cart_key = 'cart_%s' % user.id

        if count > sku.stock:
            return JsonResponse({'res': 4, 'msg': '商品库存不足'})

        print(sku_id)
        print(count)
        # 更新
        conn.hset(cart_key, sku_id, count)

        total_count = 0
        # 购物车的总件数
        vals = conn.hvals(cart_key)
        print(vals)
        for count in vals:
            total_count += int(count)
        print(total_count)
        return JsonResponse({'res': 6, 'total_count': total_count, 'msg': '更新成功'})


# /cart/delete
class CartDeleteView(View):
    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 5, 'msg': '请先登录'})

        sku_id = request.POST.get('sku_id')
        if not sku_id:
            return JsonResponse({'res': 0, 'msg': '数据不完整'})

        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 1, 'msg': '商品不存在'})

        conn = get_redis_connection('default')
        cart_key = 'cart_%s' % user.id
        conn.hdel(cart_key, sku_id)

        vals = conn.hvals(cart_key)
        total_count = 0
        for count in vals:
            total_count += int(count)

        return JsonResponse({'res': 8, 'total_count': total_count, 'msg': '删除成功'})

templates/base.html
{#首页 注册 登录#}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static %}
<head>
    {% load static %}
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static "/css/reset.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "/css/main.css" %}">
    {# 网页引入文件模块 #}
    {% block topfiles %}
    {% endblock topfiles %}
</head>
<body>
{% block header_con %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">
                {% if user.is_authenticated %}
                    <div class="login_btn fl">
                        欢迎您：<em>{{ user.username }}</em>
                        <a href={% url "user:logout" %}>退出</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href={% url "user:login" %}>登录</a>
                        <span>|</span>
                        <a href={% url "user:register" %}>注册</a>
                    </div>
                {% endif %}


                <div class="user_link fl">
                    <span>|</span>
                    <a href={% url 'user:index' %}>用户中心</a>
                    <span>|</span>
                    <a href={% url 'cart:show' %}>我的购物车</a>
                    <span>|</span>
                    sf
                    <a href{% url 'user:order' 1 %}>我的订单</a>
                </div>
            </div>
        </div>
    </div>
{% endblock header_con %}

{# 网页顶部搜索框块 #}
{% block search_bar %}
    <div class="search_bar clearfix">
        <a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static "/images/logo.png" %}"></a>
        <div class="search_con fl">
            <form action="/search" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
        </div>
        <div class="guest_cart fr">
            <a href="#" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
        </div>
    </div>
{% endblock search_bar %}


{#网页主题内容块#}
{% block body %}
{% endblock body %}


<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>


{#网页底部html元素块#}
{% block bottom %}
{% endblock bottom %}
{# 网页底部引入文件块 #}
{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}天天生鲜-首页{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static "/js/jquery-1.12.4.min.js" %}"></script>
    <script type="text/javascript" src="{% static "/js/jquery-ui.min.js" %}"></script>
    <script type="text/javascript" src="{% static "/js/slide.js" %}"></script>
{% endblock topfiles %}
</head>
<body>

{% block body %}
    <div class="center_con clearfix">
        <ul class="subnav fl">
            {% for type in types %}
                <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
        </ul>
        <div class="slide fl">
            <ul class="slide_pics">
                {% for banner in goods_banners %}
                    <li><img src={{ banner.image.url }} style="width:760px;height:270px;" alt="幻灯片"></li>
                {% endfor %}
            </ul>
            <div class="prev"></div>
            <div class="next"></div>
            <ul class="points"></ul>
        </div>
        <div class="adv fl">
            {% for banner in promotion_banners %}
                <a href={{ banner.url }}><img src={{ banner.image.url }}></a>
            {% endfor %}
        </div>
    </div>

    {% for type in types %}
        <div class="list_model">
            <div class="list_title clearfix">
                <h3 class="fl" id="model01">{{ type.name }}</h3>
                <div class="subtitle fl">
                    <span>|</span>
                    {% for title_banner in type.title_banners %}
                        <a href={% url 'goods:detail' title_banner.sku.id %}>{{ title_banner.sku.name }}</a>
                    {% endfor %}
                </div>
                <a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
            </div>

            <div class="goods_con clearfix">
                <div class="goods_banner fl"><img src={{ type.image.url }}></div>
                <ul class="goods_list fl">
                    {% for banner in type.image_banners %}
                        <li>
                            <h4><a href={% url 'goods:detail' banner.sku.id %}>{{ banner.sku.name }}</a></h4>
                            <a href={% url 'goods:detail' banner.sku.id %}><img src={{ banner.sku.image.url }}></a>
                            <div class="prize">¥ {{ banner.sku.price }}</div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endfor %}


{% endblock %}
{% block bottom %}
    <script type="text/javascript" src="js/slideshow.js"></script>
    <script type="text/javascript">
        BCSlideshow('focuspic');
        var oFruit = document.getElementById('fruit_more');
        var oShownum = document.getElementById('show_count');

        var hasorder = localStorage.getItem('order_finish');

        if (hasorder) {
            oShownum.innerHTML = '2';
        }

        oFruit.onclick = function () {
            window.location.href = 'list.html';
        }
    </script>
{% endblock %}
</body>
</html>

templates/user_center_info.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    {% load static %}
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>天天生鲜-用户中心</title>
    <link rel="stylesheet" type="text/css" href={% static "/css/reset.css" %}>
    <link rel="stylesheet" type="text/css" href={% static "/css/main.css" %}>
</head>
<body>
<div class="header_con">
    <div class="header">
        <div class="welcome fl">欢迎来到天天生鲜!</div>
        <div class="fr">
            {% if user.is_authenticated %}
                <div class="login_btn fl">
                    欢迎您：<em>{{ user.username }}</em>
                    <a href={% url "user:register" %}>退出</a>
                </div>
            {% else %}
                <div class="login_btn fl">
                    <a href="login.html">登录</a>
                    <span>|</span>
                    <a href="register.html">注册</a>
                </div>
            {% endif %}

            <div class="user_link fl">
                <span>|</span>
                <a href={% url 'user:index' %}>用户中心</a>
                <span>|</span>
                <a href="{% url 'cart:show' %}">我的购物车</a>
                <span>|</span>
                <a href={% url 'order:place' %}>我的订单</a>
            </div>
        </div>
    </div>
</div>

<div class="search_bar clearfix">
    <a href="index1.html" class="logo fl"><img src={% static "/images/logo.png" %}></a>
    <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
    <div class="search_con fr">
        <input type="text" class="input_text fl" name="" placeholder="搜索商品">
        <input type="button" class="input_btn fr" name="" value="搜索">
    </div>
</div>

<div class="main_con clearfix">
    <div class="left_menu_con clearfix">
        <h3>用户中心</h3>
        <ul>
            <li><a href={% url "user:index" %} class="active">· 个人信息</a></li>
            <li><a href={% url "user:order" 1 %}>· 全部订单</a></li>
            <li><a href={% url "user:address" %}>· 收货地址</a></li>
        </ul>
    </div>
    <div class="right_content clearfix">
        <div class="info_con clearfix">
            <h3 class="common_title2">基本信息</h3>
            <ul class="user_info_list">
                {% if address %}
                    <li><span>用户名：</span>{{ user.username }}</li>
                    <li><span>联系方式：</span>{{ address.phone }}</li>
                    <li><span>联系地址：</span>{{ address.addr }}</li>
                {% else %}
                    <li><span>用户名：</span>{{ address.username }}</li></br>
                    <li><span>没有联系地址</span></li>
                {% endif %}
            </ul>
        </div>

        <h3 class="common_title2">最近浏览</h3>
        <div class="has_view_list">
            <ul class="goods_type_list clearfix">
                {% for goods in goods_li %}
                    <li>
                        <a href={% url 'goods:detail' goods.id %}><img src={{ goods.image.url }}></a>
                        <h4><a href={% url 'goods:detail' goods.id %}>{{ goods.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ goods.price }}</span>
                            <span class="unit">{{ goods.price }}/{{ goods.unite }}g</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% empty %}
                    <li>没有浏览记录</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>


<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>

</body>
</html>

templates/user_center_order.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    {% load static %}
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>天天生鲜-用户中心</title>
    <link rel="stylesheet" type="text/css" href={% static "/css/reset.css" %}>
    <link rel="stylesheet" type="text/css" href={% static "/css/main.css" %}>
    {% csrf_token %}
</head>
<body>
<div class="header_con">
    <div class="header">
        <div class="welcome fl">欢迎来到天天生鲜!</div>
        <div class="fr">
            {% if user.is_authenticated %}
                <div class="login_btn fl">
                    欢迎您：<em>{{ user.username }}</em>
                    <a href={% url "user:register" %}>退出</a>
                </div>
            {% else %}
                <div class="login_btn fl">
                    <a href="login.html">登录</a>
                    <span>|</span>
                    <a href="register.html">注册</a>
                </div>
            {% endif %}
            <div class="user_link fl">
                <span>|</span>
                <a href="user_center_info.html">用户中心</a>
                <span>|</span>
                <a href="cart.html">我的购物车</a>
                <span>|</span>
                <a href="user_center_order.html">我的订单</a>
            </div>
        </div>
    </div>
</div>

<div class="search_bar clearfix">
    <a href="{% url 'goods:index' %}" class="logo fl"><img src={% static "/images/logo.png" %}></a>
    <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
    <div class="search_con fr">
        <input type="text" class="input_text fl" name="" placeholder="搜索商品">
        <input type="button" class="input_btn fr" name="" value="搜索">
    </div>
</div>

<div class="main_con clearfix">
    <div class="left_menu_con clearfix">
        <h3>用户中心</h3>
        <ul>
            <li><a href={% url "user:index" %}>· 个人信息</a></li>
            <li><a href={% url "user:order" 1 %} class="active">· 全部订单</a></li>
            <li><a href={% url "user:address" %}>· 收货地址</a></li>
        </ul>
    </div>
    <div class="right_content clearfix">
        <h3 class="common_title2">全部订单</h3>
        {% for order in  order_page %}
            <ul class="order_list_th w978 clearfix">
                <li class="col01">{{ order.create_time }}</li>
                <li class="col02">订单号：{{ order.order_id }}</li>
                <li class="col02 stress">{{ order.status_name }}</li>
            </ul>
            <table class="order_list_table w980">
                <tbody>
                <tr>
                    <td width="55%">
                        {% for order_sku in order.order_skus %}
                            <ul class="order_goods_list clearfix">
                                <li class="col01"><img src={{ order_sku.sku.image.url }}></li>
                                <li class="col02">{{ order_sku.sku.name }}<em>{{ order_sku.price }}元/{{ order_sku.sku.unite }}</em>
                                </li>
                                <li class="col03">{{ order_sku.count }}</li>
                                <li class="col04">{{ order_sku.amount }}元</li>
                            </ul>
                        {% endfor %}

                    </td>
                    <td width="15%">{{ order.total_price|add:order.transit_price }}(含运费:{{ order.transit_price }})元</td>
                    <td width="15%">{{ order.status_name }}</td>
                    <td width="15%"><a href="#" order_id="{{ order.order_id }}" status="{{ order.order_status }}"
                                       class="oper_btn">去付款</a></td>
                </tr>
                </tbody>
            </table>
        {% endfor %}
        <div class="pagenation">
            {% if order_page.has_previous_page %}
                <a href="{% url 'user:order' order_page.previous_page_number %}">上一页</a>
            {% endif %}
            {% for pindex in pages %}
                {% if pindex == order_page.number %}
                    <a href="{% url 'user:order' pindex %}" class="active">{{ pindex }}</a>
                {% else %}
                    <a href="{% url 'user:order' pindex %}">{{ pindex }}</a>
                {% endif %}
            {% endfor %}
            {% if order_page.has_next_page %}
                <a href={% url 'user:order' order_page.next_page_number %}>下一页></a>
            {% endif %}
        </div>
    </div>
</div>


<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>

</body>
<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script type="text/javascript">
    $('.oper_btn').click(function () {
        status = $(this).attr('status')
        if (status == 1) {
            order_id = $(this).attr('order_id')
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            params = {'order_id': order_id, 'csrfmiddlewaretoken': csrf}
            $.post('/order/pay', params, function (data) {
                if (data.code == 125) {
                    window.open(data.pay_url)
                    // 浏览器访问/order/check接口获取支付结果
                    $.post('/order/check', params, function (data) {
                        if (data.code == 1) {
                            // 支付成功
                            alert('支付成功')
                            location.reload()
                        }
                    });
                } else {
                    alert(data.msg)
                }
            })
        } else {
            alert('其他情况')
        }
    })
</script>
</html>










templates/user_center_site.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    {% load static %}
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>天天生鲜-用户中心</title>
    <link rel="stylesheet" type="text/css" href={% static "/css/reset.css" %}>
    <link rel="stylesheet" type="text/css" href={% static "/css/main.css" %}>
</head>
<body>
<div class="header_con">
    <div class="header">
        <div class="welcome fl">欢迎来到天天生鲜!</div>
        <div class="fr">
            {% if user.is_authenticated %}
                <div class="login_btn fl">
                    欢迎您：<em>{{ user.username }}</em>
                    <a href={% url "user:logout" %}>退出</a>
                </div>
            {% else %}
                <div class="login_btn fl">
                    <a href={% url "user:login" %}>登录</a>
                    <span>|</span>
                    <a href={% url "user:register" %}>注册</a>
                </div>
            {% endif %}
            <div class="user_link fl">
                <span>|</span>
                <a href={% url "user:index" %}>用户中心</a>
                <span>|</span>
                <a href={% url 'cart:show' %}>我的购物车</a>
                <span>|</span>
                <a href={% url "user:order" %}>我的订单</a>
            </div>
        </div>
    </div>
</div>

<div class="search_bar clearfix">
    <a href="index1.html" class="logo fl"><img src={% static "/images/logo.png" %}></a>
    <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
    <div class="search_con fr">
        <input type="text" class="input_text fl" name="" placeholder="搜索商品">
        <input type="button" class="input_btn fr" name="" value="搜索">
    </div>
</div>

<div class="main_con clearfix">
    <div class="left_menu_con clearfix">
        <h3>用户中心</h3>
        <ul>
            <li><a href={% url "user:index" %}>· 个人信息</a></li>
            <li><a href={% url "user:order" %}>· 全部订单</a></li>
            <li><a href={% url "user:address" %} class="active">· 收货地址</a></li>
        </ul>
    </div>
    <div class="right_content clearfix">
        <h3 class="common_title2">收货地址</h3>
        <div class="site_con">
            <dl>
                <dt>当前地址：</dt>
                {% if address %}
                    <dd>{{ address.addr }} （{{ address.receiver }} 收） {{ address.phone}}</dd>
                {% else %}
                    <dd>没有默认地址</dd>
                {% endif %}
            </dl>
        </div>
        <h3 class="common_title2">编辑地址</h3>
        <div class="site_con">
            <form method="post">
                {% csrf_token %}
                <div class="form_group">
                    <label>收件人：</label>
                    <input type="text" name="receiver">
                </div>
                <div class="form_group form_group2">
                    <label>详细地址：</label>
                    <textarea class="site_area" name="addr"></textarea>
                </div>
                <div class="form_group">
                    <label>邮编：</label>
                    <input type="text" name="zip_code">
                </div>
                <div class="form_group">
                    <label>手机：</label>
                    <input type="text" name="phone">
                </div>
                <input type="submit" name="" value="提交" class="info_submit">
            </form>
        </div>
        {{ error }}
    </div>
</div>


<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>

</body>
</html>